spring:
  application:
    name: global-config

message: "Hello from Config Server - Global"

jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxPGDBzLlKX5zv1dsUwYa
    QEKXtBO7+58vpwUHCT7owPXVefepGTLtdHotnobJOjQFVXGBgSgDbuNKaxrTqSXK
    hZXO8Nl8BCuujbV7x9Ju8ELLyKnslDkSJy+wiFD7EvhOxsAtvVrBI2FEruDGrNTt
    kZ+FdhGugEeTRrhQOCXGDPLIKBnyQbvGpwjdxbLR309eri14NawuQEaSK0WVmcjA
    DuDsxVUPwmlmXUSo2St23LVhNx+kAj61LfjLTK7XnIuEdoqN2YswMkrMnQHKRoSe
    1gjGKvQ5ZApD+rXKHliAZZ43/NGGXdMaEYPzzoxtF2xF9FS9LJJLwmOhqpIJeTHZ
    cQIDAQAB
    -----END PUBLIC KEY-----

logging:
  level:
    root: INFO  # Default for app
    org.springframework.cloud.netflix.eureka: DEBUG  # Eureka registration/discovery
    com.netflix.discovery: DEBUG  # Eureka client details (registry fetches)
    org.springframework.cloud.openfeign: DEBUG  # Feign requests/responses
    org.springframework.cloud.loadbalancer: TRACE  # Cache keys and instance selection
    org.springframework.cloud.client.discovery: TRACE  # DiscoveryClient operations
    org.springframework.web: INFO  # Web requests
