spring:
  application:
    name: B-AUTH-SERVICE
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8069

eureka:
  instance:
    metadata-map:
      profile: test

management:
  endpoints:
    web:
      exposure:
        include: health
