spring:
  application:
    name: B-ORDER-SERVICE
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/ordersdb_test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cache:
    type: redis

  redis:
    host: localhost         # Redis host (docker-compose service name if using docker)
    port: 6379
    lettuce:
      shutdown-timeout: 100ms
    timeout: 60000ms

server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always
  message: "Hello from Order Service Config - Test Profile (MySQL)"

eureka:
  instance:
    metadata-map:
      profile: test

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakerevents,loggers,metrics
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      userService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      userService:
        max-attempts: 3
        wait-duration: 500ms

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
