spring:
  application:
    name: B-ORDER-SERVICE
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/ordersdb_test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always
  message: "Hello from Order Service Config - Test Profile (MySQL)"

eureka:
  instance:
    metadata-map:
      profile: test


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.example.demo: DEBUG   # enable detailed logs for your app
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG             # show SQL queries
    org.hibernate.type.descriptor.sql: TRACE  # show SQL parameters
