spring:
  application:
    name: B-USER-SERVICE
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb_test
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'Asia/Kolkata'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  cache:
    type: redis
  redis:
    host: redis    # docker-compose service name
    port: 6379
    timeout: 60000

server:
  port: 8089
  error:
    include-message: always
    include-binding-errors: always

eureka:
  instance:
    metadata-map:
      profile: test

message: "Hello from User Service - Test Profile"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.example.demo: DEBUG   # enable detailed logs for your app
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG             # show SQL queries
    org.hibernate.type.descriptor.sql: TRACE  # show SQL parameters
