spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/usersdb_test
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'Asia/Kolkata'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8089

eureka:
  instance:
    metadata-map:
      profile: test


message: "Hello from User Service - Test Profile"

management.endpoints.web.exposure.include: health
management.endpoint.health.show-details: always

spring.security.user.name: test
spring.security.user.password: test123

server.error.include-message: always
server.error.include-binding-errors: always

logging.level.org.springframework.web: DEBUG
logging.level.com.example.demo: DEBUG
